# Generated by Django 2.2.4 on 2020-07-19 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='none', max_length=150)),
                ('company_name', models.CharField(default='none', max_length=150)),
                ('email', models.CharField(default='none', max_length=150)),
                ('country', models.CharField(default='none', max_length=150)),
                ('phone', models.CharField(default='none', max_length=150)),
                ('address', models.CharField(default='none', max_length=150)),
                ('order_note', models.CharField(default='none', max_length=150)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
