# Generated by Django 2.2.4 on 2020-07-19 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image_1', models.ImageField(upload_to='product/images/')),
                ('image_2', models.ImageField(upload_to='product/images/')),
                ('image_3', models.ImageField(upload_to='product/images/')),
                ('image_4', models.ImageField(upload_to='product/images/')),
                ('description', models.TextField(default='none')),
                ('specification', models.TextField(default='none')),
                ('category', models.CharField(max_length=150)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('old_price', models.IntegerField(blank=True, default=0, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('shipping_charge', models.IntegerField(blank=True, null=True)),
                ('dimension', models.CharField(max_length=150)),
                ('delivery_info', models.CharField(default='none', max_length=150)),
                ('slug', models.SlugField(default='rayslug', unique=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(default='none')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReviewConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('review', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.Review')),
            ],
        ),
        migrations.CreateModel(
            name='ProductQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Quantity')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.ManyToManyField(through='product.ProductReviewConnector', to='product.Review'),
        ),
    ]
