# Generated by Django 2.2.4 on 2020-08-08 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productquantity_shipping_charge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productquantity',
            old_name='shipping_charge',
            new_name='total_shipping_charge',
        ),
    ]
