# Generated by Django 2.2.4 on 2020-08-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200808_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_charge',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
