# Generated by Django 2.2.4 on 2020-08-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200811_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='threshold',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
