# Generated by Django 3.1.1 on 2020-09-23 02:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1050)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=1050)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1050)),
                ('description', models.TextField(default='none')),
                ('image_1', models.ImageField(blank=True, upload_to='poll_product/images/')),
                ('image_2', models.ImageField(blank=True, upload_to='poll_product/images/')),
                ('image_3', models.ImageField(blank=True, upload_to='poll_product/images/')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PollOptionConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('option', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='poll.option')),
                ('poll', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='poll.poll')),
            ],
        ),
        migrations.CreateModel(
            name='PollCommentConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='poll.comment')),
                ('poll', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='poll.poll')),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='comments',
            field=models.ManyToManyField(through='poll.PollCommentConnector', to='poll.Comment'),
        ),
        migrations.AddField(
            model_name='poll',
            name='options',
            field=models.ManyToManyField(through='poll.PollOptionConnector', to='poll.Option'),
        ),
    ]
