# Generated by Django 3.1.1 on 2020-09-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
