# Generated by Django 3.1.1 on 2020-09-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_option_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='category',
            field=models.CharField(default='section_one', max_length=1050),
        ),
        migrations.AddField(
            model_name='poll',
            name='count_down',
            field=models.CharField(default='July 21, 2020 23:00:00', max_length=1050),
        ),
        migrations.AddField(
            model_name='poll',
            name='tag_title',
            field=models.CharField(default='Review', max_length=1050),
        ),
    ]
