# Generated by Django 3.1.1 on 2020-09-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20200924_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='user_id',
            field=models.CharField(default='none', max_length=1050),
        ),
    ]
