# Generated by Django 3.1.1 on 2020-09-18 09:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=150)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cart', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
